# LOCATION: spark-k8s-project/spark-rbac.yaml
# --- ENTIRE FILE CONTENT ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: default
rules:
# Permissions needed by the driver pod to manage executor pods & cleanup
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "create", "get", "list", "watch", "delete", "deletecollection" ]
- apiGroups: [ "" ]
  resources: [ "services", "configmaps" ]
  verbs: [ "create", "get", "list", "delete", "deletecollection" ]
# Optional: Permissions for PersistentVolumeClaims if used (good to include)
- apiGroups: [ "" ]
  resources: [ "persistentvolumeclaims" ]
  verbs: [ "create", "get", "list", "delete", "deletecollection" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spark # The ServiceAccount created above
  namespace: default
roleRef:
  kind: Role # Granting the Role defined above
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

# --- END OF FILE CONTENT ---
